# FlowCode Credit Analytics - Base Configuration

paths:
  data_dir: "data/"
  raw_dir: "data/raw/"
  processed_dir: "data/processed/"
  output_dir: "output/"

defaults:
  date_format: "%Y-%m-%d"
  trading_days_per_year: 252

ratings:
  ig_threshold: "BBB-"  # Investment grade: BBB- and above
  rating_order:
    - "AAA"
    - "AA+"
    - "AA"
    - "AA-"
    - "A+"
    - "A"
    - "A-"
    - "BBB+"
    - "BBB"
    - "BBB-"
    - "BB+"
    - "BB"
    - "BB-"
    - "B+"
    - "B"
    - "B-"
    - "CCC+"
    - "CCC"
    - "CCC-"
    - "CC"
    - "C"
    - "D"
